name: patient_alert_app
description: A Patient Alert System mobile application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.1
  intl: ^0.18.1
  flutter_svg: ^2.0.9
  url_launcher: ^6.2.1
  permission_handler: ^11.0.1
  path_provider: ^2.1.1
  audio_waveforms: ^1.0.5
  mime: ^1.0.4
  dio: ^5.4.0
  jwt_decoder: ^2.0.1
  package_info_plus: ^4.2.0
  device_info_plus: ^9.1.1
  dio_cache_interceptor: ^3.5.1
  dio_cache_interceptor_hive_store: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  # Assets section for images and other resources
  assets:
    - assets/images/mom_care_logo.jpg

# Flutter Launcher Icons configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/mom_care_logo.jpg"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/mom_care_logo.jpg"
    background_color: "#BC77E4"
    theme_color: "#BC77E4"
  windows:
    generate: true
    image_path: "assets/images/mom_care_logo.jpg"
    icon_size: 48 